/**
 * Terms of Service and Privacy Policy copy.
 *
 * This is plain-language template wording written to match the product as
 * described elsewhere in this repo. It is NOT legal advice and has not been
 * reviewed by counsel — have a lawyer review it before the site goes live.
 */

import { ADDRESS_LINES, SITE } from "../site";

export interface LegalSection {
  id: string;
  heading: string;
  paragraphs?: string[];
  bullets?: string[];
}

export const LEGAL_UPDATED = "June 15, 2026";

const CONTACT_BLOCK = [
  SITE.legalName,
  ...ADDRESS_LINES,
  SITE.phones[0],
].join(" · ");

export const TERMS: LegalSection[] = [
  {
    id: "agreement",
    heading: "1. Agreement to Terms",
    paragraphs: [
      `These Terms of Service ("Terms") form a binding agreement between you and ${SITE.legalName} ("${SITE.name}", "we", "us" or "our") and govern your access to and use of our practice-management platform, websites and related services (together, the "Service").`,
      "By creating an account, accessing the Service, or clicking to accept these Terms, you agree to be bound by them. If you are entering into these Terms on behalf of a firm or other organisation, you represent that you have authority to bind that organisation, and \"you\" refers to that organisation.",
      "If you do not agree to these Terms, do not use the Service.",
    ],
  },
  {
    id: "the-service",
    heading: "2. The Service",
    paragraphs: [
      "The Service provides accounting practices with client records, service catalogues, task and workflow management, compliance deadline tracking, engagement letters with electronic signature, a client portal, reporting and related functionality.",
      "We may add, change or remove features over time. We will not make a change that materially reduces the core functionality of a paid plan during a term you have already paid for without giving you notice and, where the change is material and adverse, the option to cancel and receive a pro-rated refund.",
    ],
  },
  {
    id: "accounts",
    heading: "3. Accounts and access",
    paragraphs: [
      "You must provide accurate account information and keep it current. You are responsible for all activity under your account and for the confidentiality of your credentials.",
      "You are responsible for the acts and omissions of the users you invite, including staff and any client-portal users. You must promptly notify us of any unauthorised access or suspected security incident affecting your account.",
    ],
    bullets: [
      "Do not share credentials between individuals — provision a user per person.",
      "Deactivate users promptly when they leave your organisation.",
      "Enable multi-factor authentication where the Service offers it.",
    ],
  },
  {
    id: "acceptable-use",
    heading: "4. Acceptable use",
    paragraphs: ["You agree not to:"],
    bullets: [
      "Use the Service in violation of any applicable law or professional obligation.",
      "Upload material you do not have the right to upload, or that infringes another party's rights.",
      "Attempt to access data belonging to another tenant, or probe, scan or test the vulnerability of the Service without our prior written consent.",
      "Interfere with or disrupt the integrity or performance of the Service.",
      "Reverse engineer, decompile or attempt to derive the source code of the Service, except to the extent this restriction is prohibited by law.",
      "Resell or provide the Service to third parties except under a written white-label or reseller agreement with us.",
    ],
  },
  {
    id: "your-data",
    heading: "5. Your data",
    paragraphs: [
      "You retain all right, title and interest in the data you and your users submit to the Service (\"Customer Data\"). You grant us a limited licence to host, process, transmit and display Customer Data solely to provide and support the Service, and as otherwise permitted in our Privacy Policy.",
      "You are responsible for the accuracy and legality of Customer Data and for having the necessary rights and consents to provide it to us — including, where you upload personal information about your own clients and their personnel, the consents required under applicable privacy law.",
      "You can export your client data at any time in CSV or XLSX format. On termination we will make Customer Data available for export for 30 days, after which we may delete it in accordance with our retention schedule.",
    ],
  },
  {
    id: "professional-responsibility",
    heading: "6. Professional responsibility",
    paragraphs: [
      "The Service is a tool. It does not provide accounting, tax, legal or professional advice, and it does not assume any part of your professional obligations to your clients or to your regulator.",
      "In particular, deadline dates generated by the Service are calculated from data you enter and from general filing rules. You remain solely responsible for verifying every filing obligation, due date and remittance applicable to your clients. Do not rely on the Service as the sole control over a statutory deadline.",
    ],
  },
  {
    id: "fees",
    heading: "7. Fees, billing and trials",
    paragraphs: [
      `Paid plans are billed in advance at the price shown at the time of purchase. Unless stated otherwise, fees are quoted in ${SITE.name === "SpidNums" ? "US dollars" : "US dollars"} and exclude applicable taxes, which will be added where required.`,
      "Subscriptions renew automatically for successive terms unless cancelled before the renewal date. You may cancel at any time; cancellation takes effect at the end of the current term and you retain access until then.",
      "Free trials are provided as-is and may be modified or withdrawn. At the end of a trial, the account converts to a paid plan only if you have provided payment details and elected to continue.",
      "Except where required by law or expressly stated in these Terms, fees are non-refundable.",
    ],
  },
  {
    id: "third-parties",
    heading: "8. Third-party services",
    paragraphs: [
      "The Service relies on third-party infrastructure and service providers for hosting, authentication, email delivery and similar functions. Your use of the Service is subject to those providers' availability.",
      "If you connect the Service to a third-party product, that product's own terms and privacy practices govern it. We are not responsible for third-party products.",
    ],
  },
  {
    id: "availability",
    heading: "9. Availability and support",
    paragraphs: [
      "We aim to keep the Service available continuously, but we do not guarantee uninterrupted availability. Planned maintenance will be scheduled outside Canadian business hours where practical, and we will give notice of maintenance expected to cause material disruption.",
      "Support is provided by email during Canadian business hours to all paid plans.",
    ],
  },
  {
    id: "ip",
    heading: "10. Intellectual property",
    paragraphs: [
      `The Service, including all software, design, text, graphics and trademarks other than Customer Data and your own branding, is owned by ${SITE.legalName} or its licensors and is protected by intellectual property law.`,
      "Where you use white-label features, you grant us a limited licence to display your name, logo and brand assets within the Service and in communications the Service sends on your behalf. You retain ownership of those assets.",
      "If you send us feedback or suggestions, we may use them without restriction or obligation to you.",
    ],
  },
  {
    id: "confidentiality",
    heading: "11. Confidentiality",
    paragraphs: [
      "Each party may receive information of the other that is marked confidential or that a reasonable person would understand to be confidential. Each party will protect the other's confidential information with at least the care it uses for its own, and will not disclose it except to personnel and advisers who need it and who are bound by comparable obligations.",
      "This section does not apply to information that is or becomes public without breach, was already known without obligation, or is independently developed.",
    ],
  },
  {
    id: "warranty",
    heading: "12. Disclaimers",
    paragraphs: [
      "Except as expressly stated in these Terms, the Service is provided \"as is\" and \"as available\". To the maximum extent permitted by law, we disclaim all warranties, express or implied, including implied warranties of merchantability, fitness for a particular purpose and non-infringement.",
      "We do not warrant that the Service will be error-free, that defects will be corrected, or that the Service or the servers that make it available are free of harmful components.",
    ],
  },
  {
    id: "liability",
    heading: "13. Limitation of liability",
    paragraphs: [
      "To the maximum extent permitted by law, neither party is liable for indirect, incidental, special, consequential or punitive damages, or for lost profits, revenue, data or goodwill, arising out of or relating to these Terms or the Service, even if advised of the possibility.",
      "Our total aggregate liability arising out of or relating to these Terms or the Service will not exceed the total fees you paid to us in the twelve months preceding the event giving rise to the claim.",
      "Nothing in these Terms limits liability that cannot be limited under applicable law, including liability for fraud or for death or personal injury caused by negligence. Some jurisdictions do not allow certain limitations, so parts of this section may not apply to you.",
    ],
  },
  {
    id: "indemnity",
    heading: "14. Indemnity",
    paragraphs: [
      "You will defend and indemnify us against third-party claims arising from your Customer Data, your use of the Service in breach of these Terms, or your violation of applicable law — provided we notify you promptly, give you control of the defence, and cooperate reasonably at your expense.",
    ],
  },
  {
    id: "termination",
    heading: "15. Suspension and termination",
    paragraphs: [
      "You may terminate at any time by cancelling your subscription and closing your account. We may suspend or terminate your access if you materially breach these Terms and do not cure the breach within 15 days of notice, or immediately where the breach poses a security or legal risk.",
      "On termination your right to use the Service ends. Sections that by their nature should survive — including your data rights on export, confidentiality, disclaimers, limitation of liability, indemnity and governing law — survive termination.",
    ],
  },
  {
    id: "changes",
    heading: "16. Changes to these Terms",
    paragraphs: [
      "We may update these Terms from time to time. Where a change is material we will give at least 30 days' notice by email or in-product notice before it takes effect. Continuing to use the Service after the effective date constitutes acceptance.",
      "If you do not accept a material change, you may cancel before it takes effect and receive a pro-rated refund of prepaid fees for the remainder of the term.",
    ],
  },
  {
    id: "governing-law",
    heading: "17. Governing law and disputes",
    paragraphs: [
      "These Terms are governed by the laws of the Province of Alberta and the federal laws of Canada applicable there, without regard to conflict-of-law rules. The parties submit to the exclusive jurisdiction of the courts of Alberta.",
      "Before commencing proceedings, the parties will attempt in good faith to resolve the dispute by negotiation between representatives with authority to settle.",
    ],
  },
  {
    id: "general",
    heading: "18. General",
    paragraphs: [
      "These Terms, together with the Privacy Policy and any order form, are the entire agreement between the parties on this subject. If a provision is found unenforceable, the rest remains in effect. A failure to enforce a provision is not a waiver of it.",
      "You may not assign these Terms without our written consent. We may assign them to an affiliate or in connection with a merger, acquisition or sale of assets, on notice to you.",
      `Questions about these Terms: ${SITE.email} — ${CONTACT_BLOCK}.`,
    ],
  },
];

export const PRIVACY: LegalSection[] = [
  {
    id: "overview",
    heading: "1. Overview",
    paragraphs: [
      `${SITE.legalName} ("${SITE.name}", "we", "us") provides practice-management software to accounting firms. This policy explains what personal information we collect, why, how we protect it, and the choices you have.`,
      "We handle personal information in accordance with the Personal Information Protection and Electronic Documents Act (PIPEDA) and, where applicable, provincial privacy legislation including Alberta's PIPA, British Columbia's PIPA and Quebec's Law 25.",
    ],
  },
  {
    id: "roles",
    heading: "2. Our role: controller and processor",
    paragraphs: [
      "We act in two capacities, and the distinction matters for your rights.",
      "For information about our own customers — the firms and firm users who sign up — we determine why and how it is processed. We are the controller.",
      "For information a firm uploads about its own clients, we process it on that firm's instructions. The firm is the controller and we are the processor. If you are a client of a firm using the Service and want your information accessed, corrected or deleted, contact that firm; we will support them in responding.",
    ],
  },
  {
    id: "collect",
    heading: "3. What we collect",
    bullets: [
      "Account information: name, work email, phone, job title, firm name and role.",
      "Billing information: billing contact, address and payment method (payment card details are handled by our payment processor and are not stored on our systems).",
      "Customer Data: the client records, contacts, services, tasks, deadlines, documents and engagement letters your firm creates in the Service.",
      "Usage data: pages accessed, features used, timestamps and approximate location derived from IP address.",
      "Technical data: IP address, browser and device type, and log data.",
      "Support communications: the content of messages you send us.",
    ],
  },
  {
    id: "why",
    heading: "4. Why we use it",
    bullets: [
      "To provide, maintain and support the Service.",
      "To authenticate users and secure accounts.",
      "To bill for paid plans and manage subscriptions.",
      "To send service and security notices, which are not optional while you hold an account.",
      "To send product and marketing email, which is optional and which you can withdraw at any time.",
      "To diagnose faults, prevent abuse and improve reliability and performance.",
      "To meet legal, regulatory and professional obligations.",
    ],
  },
  {
    id: "legal-basis",
    heading: "5. Consent and legal basis",
    paragraphs: [
      "We rely on your consent, on the necessity of processing to perform our contract with you, and on legitimate interests such as securing the Service and preventing fraud.",
      "Marketing email is sent only with express or implied consent as permitted under Canada's Anti-Spam Legislation, and every marketing message carries an unsubscribe link. Withdrawing marketing consent does not stop transactional and security notices.",
    ],
  },
  {
    id: "residency",
    heading: "6. Where your data lives",
    paragraphs: [
      "Customer Data is stored in Canada, in the ca-central-1 region. Backups remain in Canada.",
      "Some sub-processors that support the Service — for example email delivery and error monitoring — may process limited technical or contact data outside Canada. Where they do, we put contractual protections in place and limit the data transferred to what the function requires.",
    ],
  },
  {
    id: "sharing",
    heading: "7. When we share information",
    paragraphs: ["We do not sell personal information. We share it only in these circumstances:"],
    bullets: [
      "With sub-processors who provide hosting, authentication, email delivery, payments and monitoring, bound by written agreements limiting their use to providing that service.",
      "Within your own firm's tenant, according to the roles your administrators assign.",
      "Where you direct it — for example, sending an engagement letter to a recipient you nominate.",
      "Where required by law, or to respond to a valid legal process. We will notify you unless legally prohibited.",
      "In connection with a merger, acquisition or sale of assets, subject to this policy continuing to apply.",
    ],
  },
  {
    id: "security",
    heading: "8. How we protect it",
    bullets: [
      "Encryption in transit (TLS) and at rest.",
      "Per-tenant isolation enforced by row-level security in the database, independently of the application layer.",
      "Asymmetric verification of session tokens against the identity provider's public keys.",
      "Role-based access control, with least privilege for our own personnel.",
      "An append-only audit log of mutations, retained for the life of the account.",
      "Regular backups with tested restores.",
    ],
    paragraphs: [
      "No system is perfectly secure. If a breach creates a real risk of significant harm, we will notify the Office of the Privacy Commissioner of Canada and affected individuals as required, and we keep a record of all breaches including those below the reporting threshold.",
    ],
  },
  {
    id: "retention",
    heading: "9. How long we keep it",
    paragraphs: [
      "We keep Customer Data for as long as your account is active. After termination, data is available for export for 30 days and is then deleted or irreversibly anonymised within 90 days, except where we must retain it to meet a legal or tax obligation.",
      "Audit logs and billing records are retained for seven years to meet Canadian record-keeping requirements. Backups are cycled out within 35 days.",
    ],
  },
  {
    id: "rights",
    heading: "10. Your rights",
    paragraphs: ["Subject to applicable law, you may:"],
    bullets: [
      "Access the personal information we hold about you.",
      "Correct information that is inaccurate or incomplete.",
      "Withdraw consent to non-essential processing, including marketing.",
      "Request deletion, where we are not required to retain the information.",
      "Request a copy of your data in a portable format.",
      "Complain to us, and to the Office of the Privacy Commissioner of Canada or your provincial regulator.",
    ],
  },
  {
    id: "cookies",
    heading: "11. Cookies",
    paragraphs: [
      "We use strictly necessary cookies to keep you signed in and to secure the Service; these cannot be switched off. We use analytics cookies to understand how the site is used, and these are set only with your consent through the banner on your first visit.",
      "You can change your choice at any time by clearing site data and reloading the page, or through your browser's cookie controls.",
    ],
  },
  {
    id: "children",
    heading: "12. Children",
    paragraphs: [
      "The Service is intended for business use and is not directed at children. We do not knowingly collect personal information from anyone under 16. If you believe we have, contact us and we will delete it.",
    ],
  },
  {
    id: "changes",
    heading: "13. Changes to this policy",
    paragraphs: [
      "We may update this policy. Where a change is material we will give notice by email or in-product notice before it takes effect. The date at the top of this page shows when it was last revised.",
    ],
  },
  {
    id: "contact",
    heading: "14. Contact us",
    paragraphs: [
      `Privacy enquiries and requests: ${SITE.privacyEmail}.`,
      `Our privacy officer can be reached at ${CONTACT_BLOCK}.`,
      "If you are not satisfied with our response, you may contact the Office of the Privacy Commissioner of Canada at priv.gc.ca, or your provincial privacy regulator.",
    ],
  },
];
